hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
scopeName: _default
collectionName: _default
metadataBucket: dcp-test-meta
dcp:
  group:
    name: groupName
    membership:
      type: static
      memberNumber: 1
      totalMembers: 1
api:
  port: 8080
metric:
  enabled: true
  path: /metrics
leaderElection:
  enabled: false
logging:
  level: info