hosts:
  - couchbase.couchbase.svc.cluster.local:8091
username: user
password: password
bucketName: dcp-test
metadataBucket: dcp-test-meta
dcp:
  group:
    name: groupName
    membership:
      type: couchbase
logging:
  level: debug