hosts:
  - couchbase.couchbase.svc.cluster.local:8091
username: user
password: password
bucketName: dcp-test
metadataBucket: dcp-test-meta
dcp:
  group:
    name: groupName
    membership:
      type: kubernetesHa
api:
  port: 8080
metric:
  enabled: true
  path: /metrics
leaderElection:
  enabled: true
  type: kubernetes
  config:
    leaseLockName: group-name-lock
    leaseLockNamespace: default
  rpc:
    port: 8081