hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
metadataBucket: dcp-test-meta
dcp:
  group:
    name: groupName
    membership:
      type: static
      memberNumber: 1
      totalMembers: 1
logging:
  level: debug