hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
metadataBucket: dcp-test-meta
dcp:
  group:
    name: groupName
    membership:
      type: kubernetesStatefulSet
      totalMembers: 1