hosts:
  - couchbase.couchbase.svc.cluster.local:8091
username: user
password: password
bucketName: dcp-test
dcp:
  group:
    name: groupName
    membership:
      type: kubernetesHa
leaderElection:
  enabled: true
  type: kubernetes
  config:
    leaseLockName: group-name-lock
    leaseLockNamespace: default