apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godcpclient
  name: godcpclient
spec:
  replicas: 4
  selector:
    matchLabels:
      app: godcpclient
  template:
    metadata:
      labels:
        app: godcpclient
    spec:
      automountServiceAccountToken: true
      serviceAccount: godcpclient-sa
      containers:
        - image: docker.io/trendyoltech/godcpclient:latest
          imagePullPolicy: Never
          name: godcpclient
          ports:
            - containerPort: 8081
              name: rpc
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: godcpclient-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: godcpclient-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: godcpclient-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: godcpclient-role
subjects:
  - kind: ServiceAccount
    name: godcpclient-sa
---
