version: "3.8"
services:
  couchbase:
    build:
      context: "test/couchbase"
    ports:
      - "8091:8091"
      - "11210:11210"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://admin:password@localhost:8091/pools/default/buckets/dcp-test" ]
      interval: 2s
      timeout: 3s
      retries: 60
    environment:
      - USERNAME=admin
      - PASSWORD=password


 # test:
 #   build:
 #     context:  "test/integration"
 #   depends_on:
 #     - couchbase
 #   links:
 #     - couchbase