apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcp
  name: dcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcp
  template:
    metadata:
      labels:
        app: dcp
    spec:
      serviceAccountName: dcp-sa # need for kubernetes leader election type
      containers:
        - image: docker.io/trendyoltech/dcp:latest # change this to your image
          imagePullPolicy: Never
          name: dcp
          ports:
            - containerPort: 8081 # need for kubernetes leader election type
              name: rpc
            - containerPort: 8080
              name: http
