apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godcpclient
  name: godcpclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godcpclient
  template:
    metadata:
      labels:
        app: godcpclient
    spec:
      automountServiceAccountToken: true  # need for kubernetes leader election type
      serviceAccount: godcpclient-sa
      containers:
        - image: docker.io/trendyoltech/godcpclient:latest # change this to your image
          imagePullPolicy: Never
          name: godcpclient
          ports:
            - containerPort: 8081 # need for kubernetes leader election type
              name: rpc
            - containerPort: 8080
              name: http
          env:
            - name: POD_IP # need for kubernetes leader election type
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME # need for kubernetes leader election type
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
