apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dcp
  name: dcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcp
  template:
    metadata:
      labels:
        app: dcp
    spec:
      automountServiceAccountToken: true  # need for kubernetes leader election type
      serviceAccount: dcp-sa
      containers:
        - image: docker.io/trendyoltech/dcp:latest # change this to your image
          imagePullPolicy: Never
          name: dcp
          ports:
            - containerPort: 8081 # need for kubernetes leader election type
              name: rpc
            - containerPort: 8080
              name: http
          env:
            - name: POD_IP # need for kubernetes leader election type
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME # need for kubernetes leader election type
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
