# need for kubernetes leader election type
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dcp-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dcp-role
subjects:
  - kind: ServiceAccount
    name: dcp-sa