# need for kubernetes leader election type
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dcp-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - patch