name: Benchmark

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Continuous Benchmarking
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_PUBLISH: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
