name: Benchmark

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Continuous Benchmarking for Go
        uses: bobheadxi/gobenchdata@v1.3.1
        with:
          PUBLISH: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
