name: 🔨 Build And Test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go get .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          args: -c .golangci.yml --timeout=5m -v

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
