name: DCP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dcp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "5.0.1", "5.1.0", "5.5.0", "6.0.0", "6.5.0", "6.6.0", "7.0.0", "7.1.0", "7.2.0", "7.2.3" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Test DCP
        run: go test -run "^\QTestDcp\E$"
        env:
          CB_VERSION: ${{ matrix.version }}
