name: Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "7.1.6", "7.2.4" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
      - name: Start cluster
        run: make create-cluster version=${{ matrix.version }}

      - name: Integration Test
        run: go test -v test/integration/integration_test.go
        env:
          INPUT_PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Delete cluster
        if: always()
        run: make delete-cluster
