name: Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
      - name: Start containers
        run: make compose

      - name: Integration Test
        run: go test -v test/integration/integration_test.go
        env:
          INPUT_PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
